version: 0.0
os: linux
files: 
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
permissions:
  - object: /var/www/html/
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: /after_install.sh
      timeout: 300
      runas: ubuntu
